# Generated by Django 5.2.8 on 2025-11-10 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_alter_producto_options_alter_proveedor_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={},
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={},
        ),
        migrations.AlterModelOptions(
            name="venta",
            options={},
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="precio_venta",
            new_name="precio",
        ),
        migrations.AddField(
            model_name="proveedor",
            name="contacto",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tienda.categoria"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tienda.proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="direccion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="empresa",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tienda.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="venta",
            name="vendido_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="DetalleVenta",
        ),
    ]
