# Generated by Django 5.2.8 on 2025-11-14 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_alter_producto_options_alter_proveedor_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venta",
            options={"verbose_name": "Venta", "verbose_name_plural": "Ventas"},
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="tienda.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="vendido_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_venta",
                        to="tienda.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="tienda.venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalles de Venta",
                "unique_together": {("venta", "producto")},
            },
        ),
    ]
