# Generated by Django 5.2.8 on 2025-11-16 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_alter_venta_options_alter_venta_cliente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={
                "ordering": ["empresa"],
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="contacto",
        ),
        migrations.AddField(
            model_name="cliente",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tienda.producto"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="tienda.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos_suministrados",
                to="tienda.proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="direccion",
            field=models.TextField(blank=True, default="Sin direccion"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(blank=True, max_length=191, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="empresa",
            field=models.CharField(default="Sin Empresa", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
    ]
